logging:
  level:
    org.springframework.web: DEBUG
# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#server:
  #port: 8761   # HTTP (Tomcat) port

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf